name: Build README with Pandoc

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Convert README.md to PDF
      run: pandoc README.md -o README.pdf
      
    - name: Convert README.md to HTML
      run: pandoc README.md -o README.html

    - name: Upload README.pdf
      uses: actions/upload-artifact@v3
      with:
        name: README-pdf
        path: README.pdf

    - name: Upload README.html
      uses: actions/upload-artifact@v3
      with:
        name: README-html
        path: README.html
