name: Build README PDF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify Node.js version

    - name: Install pandoc and wkhtmltopdf
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc wkhtmltopdf

    - name: Convert README.md to PDF using pandoc
      run: |
        echo "Converting README.md to PDF..."
        pandoc README.md -o README.pdf -V geometry:margin=2cm --pdf-engine=wkhtmltopdf
        echo "PDF conversion completed"

        # Verify PDF was created
        if [ -f "README.pdf" ]; then
          echo "PDF file created successfully"
          ls -la README.pdf
        else
          echo "Error: PDF file was not created"
          exit 1
        fi

    # Optionally, upload the artifact (the generated PDF)
    - name: Upload README.pdf
      uses: actions/upload-artifact@v4
      with:
        name: README-pdf
        path: README.pdf
