name: Build README with markdown-pdf

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify Node.js version

    - name: Install dependencies
      run: npm install puppeteer markdown-it

    - name: Convert README.md to PDF using puppeteer
      run: |
        node -e "
        const puppeteer = require('puppeteer');
        const fs = require('fs');
        const markdownit = require('markdown-it');
        const md = markdownit();

        async function convert() {
          const browser = await puppeteer.launch();
          const page = await browser.newPage();

          const markdown = fs.readFileSync('README.md', 'utf8');
          const html = md.render(markdown);

          await page.setContent(html);
          await page.pdf({ path: 'README.pdf', format: 'A4' });

          await browser.close();
        }

        convert().catch(console.error);
        "

    # Optionally, upload the artifact (the generated PDF)
    - name: Upload README.pdf
      uses: actions/upload-artifact@v4
      with:
        name: README-pdf
        path: README.pdf
