name: Build README with markdown-pdf

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify Node.js version

    - name: Install markdown-pdf
      run: npm install -g markdown-pdf

    - name: Convert README.md to PDF using markdown-pdf
      run: markdown-pdf README.md -o README.pdf

    # Optionally, upload the artifact (the generated PDF)
    - name: Upload README.pdf
      uses: actions/upload-artifact@v3
      with:
        name: README-pdf
        path: README.pdf
