name: Build README with Pandoc

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Install wkhtmltopdf
      run: sudo apt-get install -y wkhtmltopdf

    - name: Convert README.md to PDF using wkhtmltopdf
      run: pandoc README.md -o README.pdf --pdf-engine=wkhtmltopdf

    # Optionally, upload the artifact (the generated PDF)
    - name: Upload README.pdf
      uses: actions/upload-artifact@v3
      with:
        name: README-pdf
        path: README.pdf
